// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ4beZenFrQ1oy4AkQWGZPeclDRBjxeVo',
    appId: '1:68094917540:web:dcb3fbf6639fbbf21cdf31',
    messagingSenderId: '68094917540',
    projectId: 'pakisgo-37a9e',
    authDomain: 'pakisgo-37a9e.firebaseapp.com',
    storageBucket: 'pakisgo-37a9e.appspot.com',
    measurementId: 'G-YJ9D3D09HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsU3eNPTasSB3WElxCTtezQF0d6F2AbY',
    appId: '1:68094917540:android:901417c2e5a7a70d1cdf31',
    messagingSenderId: '68094917540',
    projectId: 'pakisgo-37a9e',
    storageBucket: 'pakisgo-37a9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEdLIcC-Si6b_zoV5Objfa58g33ORzB0',
    appId: '1:68094917540:ios:95dea740d838ef5e1cdf31',
    messagingSenderId: '68094917540',
    projectId: 'pakisgo-37a9e',
    storageBucket: 'pakisgo-37a9e.firebasestorage.app',
    iosBundleId: 'com.example.pakisGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWEdLIcC-Si6b_zoV5Objfa58g33ORzB0',
    appId: '1:68094917540:ios:95dea740d838ef5e1cdf31',
    messagingSenderId: '68094917540',
    projectId: 'pakisgo-37a9e',
    storageBucket: 'pakisgo-37a9e.firebasestorage.app',
    iosBundleId: 'com.example.pakisGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ4beZenFrQ1oy4AkQWGZPeclDRBjxeVo',
    appId: '1:68094917540:web:39ff96e7576c29c11cdf31',
    messagingSenderId: '68094917540',
    projectId: 'pakisgo-37a9e',
    authDomain: 'pakisgo-37a9e.firebaseapp.com',
    storageBucket: 'pakisgo-37a9e.firebasestorage.app',
    measurementId: 'G-8D9986L8WY',
  );
}
